name: Update README on gh-pages

on:
  push:
    branches:
      - main
    paths:
      - 'README.md'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Update gh-pages
        run: |
          git checkout gh-pages
          git checkout main -- README.md
          git add README.md
          git commit -m "Update README.md from main branch" || echo "No changes to commit"
          git push origin gh-pages
